### ISSUE TITLE
Missing main_background.png?

### ISSUE THREAD

**Issue by philpursglove** [FaleshSB/X-Wing-Compendium#1]
When I run the project, I immediately get a TypeInitializationException:
![image](https://cloud.githubusercontent.com/assets/1143874/26783301/5981f9c2-49ef-11e7-9356-5dbf86c05b61.png)

I don't do XAML, but am I correct in thinking there's a Misc folder missing from the repo that contains main_background.png?

**Comment by FaleshSB** [comment]
The repository only has the code, not the images. Just copy the Misc, Pilot Cards & Upgrade Cards folders from where you installed them using the releases page installer (https://github.com/FaleshSB/X-Wing-Compendium/releases) to the Bin/Debug folder, if using VS, and you should be good to go.
